### ISSUE TITLE
Blank array is returned sometimes

### ISSUE THREAD

**Issue by kriskhaira** [zautumnz/node-wifi-scanner-cli#1]
I get a blank array half the time.

```
$  node-wifi-scanner-cli
[]
$  node-wifi-scanner-cli
[]
$  node-wifi-scanner-cli
[
  {
    "ssid": "Home",
    "mac": "************",
    "channel": 1,
    "rssi": -70
  },
  ...
]
```

## Environment

- node-wifi-scanner-cli 0.0.4
- macOS 10.12.4
- node v7.8.0
- npm 4.2.0

**Comment by zautumnz** [comment]
Interesting! I'm actually not developing this anymore, as the [module this is based on](https://github.com/ancasicolica/node-wifi-scanner) has a CLI now. I thought I'd put up a deprecation notice but I guess I forgot. Could you re-open this over on their repo?

**Comment by kriskhaira** [comment]
Thanks for letting me know that node-wifi-scanner has a CLI now. As for the bug I reported, I think it's not an issue specific with your module. I faced the same behaviour using `airport -s`. Could've been my system at that time.

**Comment by kriskhaira** [comment]
Aah looks like node-wifi-scanner's CLI is actually `airport -s` so I've been using it already.
